### ISSUE TITLE
File names with extensions rst.txt

### ISSUE THREAD

**Issue by ulupo** [giotto-ai/gtda-docs#1]
Many examples can be found in `_sources`. Is this desired? I would have expected just `.rst`.

**Comment by wreise** [comment]
It is governed by a parameter `html_source_suffix`,  appended after the file extension, and by default, it is `.txt`. The general idea is to store the 'source files' and link to them from the htmls.
I just put an empty string.
It seems like [it is meant as a 'feature'](https://github.com/sphinx-doc/sphinx/pull/2454),  but i am not sure.

**Comment by ulupo** [comment]
Thanks for the clarification!

**Comment by wreise** [comment]
> I just put an empty string.

...meaning that we have sources as `.rst` files.
Can i close the issue?

**Comment by ulupo** [comment]
Yep @wreise, thanks!
